"""Insert 10 new bars (batch 4) into the bars table."""
import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))
sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])

bars = [
    {
        "google_place_id": "ChIJkaA0L3pxhlQRS7br6sCwIm4",
        "name": "The Pint Public House",
        "address": "455 Abbott St, Vancouver, BC V6B 2L2, Canada",
        "latitude": 49.2814279, "longitude": -123.1077303,
        "phone": "(604) 684-0258",
        "website": "https://vancouver.thepint.ca/",
        "opening_hours": [
            "Monday: Closed",
            "Tuesday: 3:00 PM – 1:00 AM", "Wednesday: 3:00 PM – 1:00 AM",
            "Thursday: 3:00 PM – 1:00 AM",
            "Friday: 3:00 PM – 3:00 AM", "Saturday: 3:00 PM – 3:00 AM",
            "Sunday: 3:00 PM – 1:00 AM",
        ],
        "average_rating": 4.0, "review_count": 3268,
        "neighbourhood": "Downtown", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Boisterous sports pub serving beer pitchers & classic bar bites, plus wings in 40 different sauces.",
    },
    {
        "google_place_id": "ChIJTRHlTndxhlQRNl_jlsUsokI",
        "name": "Six Acres",
        "address": "203 Carrall St, Vancouver, BC V6B 2J2, Canada",
        "latitude": 49.2833649, "longitude": -123.1044224,
        "phone": "(604) 488-0110",
        "website": "http://sixacres.ca/",
        "opening_hours": [
            "Monday: 12:00 PM – 12:00 AM", "Tuesday: 12:00 PM – 12:00 AM",
            "Wednesday: 12:00 PM – 12:00 AM", "Thursday: 9:00 AM – 12:00 AM",
            "Friday: 9:00 AM – 1:00 AM", "Saturday: 9:00 AM – 1:00 AM",
            "Sunday: 9:00 AM – 12:00 AM",
        ],
        "average_rating": 4.3, "review_count": 1368,
        "neighbourhood": "Gastown", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "This lively gastropub offers shared plates & a wide selection of beer & spirits in a historic space.",
    },
    {
        "google_place_id": "ChIJ43xubRFxhlQR-H-62xs7zjw",
        "name": "Andina Brewing Co",
        "address": "1507 Powell St, Vancouver, BC V5L 5E7, Canada",
        "latitude": 49.2836105, "longitude": -123.0738886,
        "phone": "(604) 253-2400",
        "website": "http://www.andinabrewing.ca/",
        "opening_hours": [],
        "average_rating": 4.4, "review_count": 499,
        "neighbourhood": "Railtown", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Cheery, industrial brewery serving tastings & growlers with a South American menu & live music.",
    },
    {
        "google_place_id": "ChIJ8d6cpxBxhlQRfK0TULeZq2g",
        "name": "Powell Brewery",
        "address": "1357 Powell St, Vancouver, BC V5L 1G8, Canada",
        "latitude": 49.2833264, "longitude": -123.0757859,
        "phone": "(604) 558-2537",
        "website": "http://www.powellbeer.com/",
        "opening_hours": [
            "Monday: Closed",
            "Tuesday: 2:00 – 9:00 PM", "Wednesday: 2:00 – 9:00 PM",
            "Thursday: 2:00 – 9:00 PM",
            "Friday: 12:00 – 10:00 PM", "Saturday: 12:00 – 10:00 PM",
            "Sunday: 12:00 – 8:00 PM",
        ],
        "average_rating": 4.4, "review_count": 226,
        "neighbourhood": "East Vancouver", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Boutique brewery with a relaxed tasting room pouring a selection of housemade ales & pilsners.",
    },
    {
        "google_place_id": "ChIJSTSvjuFzhlQRXNTxktdwp9U",
        "name": "The Cascade Room",
        "address": "2616 Main St, Vancouver, BC V5T 3G4, Canada",
        "latitude": 49.2617134, "longitude": -123.1006458,
        "phone": "(604) 709-8650",
        "website": "http://www.thecascade.ca/",
        "opening_hours": [
            "Monday: 4:00 – 11:00 PM", "Tuesday: 4:00 – 11:00 PM",
            "Wednesday: 4:00 – 11:00 PM", "Thursday: 4:00 – 11:00 PM",
            "Friday: 4:00 PM – 1:00 AM", "Saturday: 4:00 PM – 1:00 AM",
            "Sunday: 4:00 – 10:00 PM",
        ],
        "average_rating": 4.3, "review_count": 914,
        "neighbourhood": "South Main", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Lively eatery offers West Coast comfort fare with craft beers & an extensive classic cocktail list.",
    },
    {
        "google_place_id": "ChIJjdQkkShzhlQR5OKSMOYEgJI",
        "name": "Sing Sing Beer Bar",
        "address": "2718 Main St, Vancouver, BC V5T 3E8, Canada",
        "latitude": 49.2606765, "longitude": -123.1008233,
        "phone": "(604) 336-9556",
        "website": "https://www.freehouse.co/locations/sing-sing",
        "opening_hours": [
            "Monday: 11:30 AM – 1:00 AM", "Tuesday: 11:30 AM – 1:00 AM",
            "Wednesday: 11:30 AM – 1:00 AM", "Thursday: 11:30 AM – 1:00 AM",
            "Friday: 11:30 AM – 2:00 AM", "Saturday: 11:30 AM – 2:00 AM",
            "Sunday: 11:30 AM – 1:00 AM",
        ],
        "average_rating": 4.3, "review_count": 1864,
        "neighbourhood": "South Main", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Lively, late-night watering hole serving craft beer & Asian comfort fare in a lofty, modern space.",
    },
    {
        "google_place_id": "ChIJ5RKyJG1xhlQRCRMrZwEMF6o",
        "name": "Strathcona Beer Company",
        "address": "895 E Hastings St, Vancouver, BC V6A 1R8, Canada",
        "latitude": 49.2812549, "longitude": -123.0850595,
        "phone": "(778) 379-9050",
        "website": "https://www.strathconabeer.com/",
        "opening_hours": [
            "Monday: 12:00 – 10:00 PM", "Tuesday: 12:00 – 10:00 PM",
            "Wednesday: 12:00 – 10:00 PM", "Thursday: 12:00 – 10:00 PM",
            "Friday: 12:00 PM – 12:00 AM", "Saturday: 12:00 PM – 12:00 AM",
            "Sunday: 12:00 – 10:00 PM",
        ],
        "average_rating": 4.4, "review_count": 551,
        "neighbourhood": "Strathcona", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Ultra-modern, industrial setting for pairing house-brewed craft beers with pizza.",
    },
    {
        "google_place_id": "ChIJ92h_MmJxhlQRmP1gb313vwM",
        "name": "Tap & Barrel Olympic Village",
        "address": "75 Athletes Way, Vancouver, BC V5Y 0E4, Canada",
        "latitude": 49.2717127, "longitude": -123.1061032,
        "phone": "(604) 685-2223",
        "website": "http://tapandbarrel.com/",
        "opening_hours": [
            "Monday: 11:00 AM – 12:00 AM", "Tuesday: 11:00 AM – 12:00 AM",
            "Wednesday: 11:00 AM – 12:00 AM", "Thursday: 11:00 AM – 12:00 AM",
            "Friday: 11:00 AM – 1:00 AM",
            "Saturday: 10:00 AM – 1:00 AM", "Sunday: 10:00 AM – 12:00 AM",
        ],
        "average_rating": 4.2, "review_count": 3787,
        "neighbourhood": "False Creek", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Contemporary pub offering Pacific Northwest fare, craft brews & a sprawling patio with scenic views.",
    },
    {
        "google_place_id": "ChIJNVqaO3FxhlQRFZhv3GFvcbc",
        "name": "The Narrow Lounge",
        "address": "1898 Main St, Vancouver, BC V5T 3B9, Canada",
        "latitude": 49.268354, "longitude": -123.1004118,
        "phone": None,
        "website": "https://narrowgroup.ca/project/the-narrow/",
        "opening_hours": [
            "Monday: 5:00 PM – 1:00 AM", "Tuesday: 5:00 PM – 1:00 AM",
            "Wednesday: 5:00 PM – 1:00 AM", "Thursday: 5:00 PM – 1:00 AM",
            "Friday: 5:00 PM – 2:00 AM", "Saturday: 5:00 PM – 2:00 AM",
            "Sunday: 5:00 PM – 1:00 AM",
        ],
        "average_rating": 4.4, "review_count": 1120,
        "neighbourhood": "Mount Pleasant", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Hip, dimly lit lounge pairing cocktails with elevated bar eats like flatbreads, tacos & sandwiches.",
    },
    {
        "google_place_id": "ChIJR-oj79ZzhlQRPxQ0DJ-fZRI",
        "name": "The Flying Pig Yaletown",
        "address": "1168 Hamilton St, Vancouver, BC V6B 2S2, Canada",
        "latitude": 49.2750232, "longitude": -123.121994,
        "phone": "(604) 568-1344",
        "website": "http://theflyingpigvan.com/",
        "opening_hours": [
            "Monday: 3:00 – 11:00 PM", "Tuesday: 3:00 – 11:00 PM",
            "Wednesday: 3:00 – 11:00 PM", "Thursday: 3:00 – 11:00 PM",
            "Friday: 11:30 AM – 12:00 AM", "Saturday: 11:30 AM – 12:00 AM",
            "Sunday: 11:30 AM – 11:00 PM",
        ],
        "average_rating": 4.3, "review_count": 2713,
        "neighbourhood": "Yaletown", "price_tier": 2,
        "is_permanently_closed": False,
        "google_summary": "Canadian standards often come with a twist at this bistro in a hip, bustling space.",
    },
]

for bar in bars:
    existing = sb.table("bars").select("id").eq("google_place_id", bar["google_place_id"]).execute().data
    if existing:
        print(f"  already exists: {bar['name']} ({existing[0]['id']})")
        continue
    result = sb.table("bars").insert(bar).execute()
    print(f"  inserted: {bar['name']} → {result.data[0]['id']}")
